### ISSUE TITLE
Evaluation on test server

### ISSUE THREAD

**Issue by lxtGH** [lixincn2015/Partial-Order-Pruning#2]
Hi! Nice work! I wonder did you use multi-scale test/single crop test when submitting on test server?

**Comment by lixincn2015** [comment]
No, we do NOT use multi-scale testing (or flipping) when submitting on test
server.

We have release our model, you can obtain the same single view testing
results on validation set.

Latou <notifications@github.com> 于2019年3月23日周六 上午10:24写道：
