### ISSUE TITLE
The author gives the wrong prototxt

### ISSUE THREAD

**Issue by lesleelichong** [lixincn2015/Partial-Order-Pruning#3]
The author gives the wrong prototxt
layer {
  name: "psp.pool1.interp"
  type: "Interp"
  bottom: "psp.pool1.conv/bn"
  top: "psp.pool1.interp"
  include {
    phase: TEST
  }
  phase: TEST
  interp_param {
    height: 32
    width: 64
  }
}

we can insert 
 clip_param {
    max: 1
    min: 1
  }
to run it

layer {
  name: "psp.pool1.interp"
  type: "Interp"
  bottom: "psp.pool1.conv/bn"
  top: "psp.pool1.interp"
  include {
    phase: TEST
  }
  phase: TEST
  interp_param {
    height: 32
    width: 64
  }
  clip_param {
    max: 1
    min: 1
  }
}

**Comment by lixincn2015** [comment]
I have no idea what "clip_param" is, but i am glad it worked our for you.

As for "Interp" layer, please refer to deeplab_v2 code:
https://bitbucket.org/aquariusjay/deeplab-public-ver2/src/071ef5a59aad8d9e6e1f5b8dff3d7a5c984a3d3a/src/caffe/layers/interp_layer.cpp?at=master&fileviewer=file-view-default

It is a widely used layer type in semantic segmentation.

**Comment by lixincn2015** [comment]
We now provide the code of interp layer. 
There is no "clip_param" in our code, and I have no idea what it is.

**Comment by lixincn2015** [comment]
Please use caffe-1.0
