### ISSUE TITLE
PyTorch Version of DFNetv1&v2

### ISSUE THREAD

**Issue by donnyyou** [lixincn2015/Partial-Order-Pruning#6]
https://github.com/donnyyou/torchcv
I have trained the models on imagenet with DFNetv1 70.71 & v2 74.51. They are better than the performance that the paper report with a big gap!

**Comment by donnyyou** [comment]
https://github.com/donnyyou/torchcv/blob/master/scripts/cls/imagenet/run_ic_dfnetv2_imagenet_cls.sh

**Comment by lixincn2015** [comment]
Great!
Thank you for your models!
@donnyyou
